# Build image:
# docker build --no-cache --progress=plain -f c3-ubi/Containerfile -t c3/c3-ubi:$(cat version.x.txt).$(cat version.y.txt) . 
# podman build --no-cache --progress=plain -f c3-ubi/Containerfile -t c3/c3-ubi:$(cat version.x.txt).$(cat version.y.txt) . 

# Log in, tag and push to ECR:
# AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
# AWS_REGION=$(aws configure get region)
# aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
# docker tag c3-ubi:$(cat version.x.txt).$(cat version.y.txt) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/c3-ubi:$(cat version.x.txt).$(cat version.y.txt)
# docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/c3-ubi:$(cat version.x.txt).$(cat version.y.txt)  

# Log in, tag and push to docker hub:
# docker tag c3-ubi:$(cat version.x.txt).$(cat version.y.txt) $REGISTRY_USERNAME/c3-ubi:$(cat version.x.txt).$(cat version.y.txt)
# docker push docker.io/$REGISTRY_USERNAME/c3-ubi:$(cat version.x.txt).$(cat version.y.txt)

ARG UBI="public.ecr.aws/amazoncorretto/amazoncorretto:25-jdk"
FROM ${UBI}

# Root level
USER root
RUN dnf update -y
RUN dnf install -y "make" "maven"

## Create User
ARG USERNAME=code
ENV USERNAME=${USERNAME}
ARG USER_UID=1001
RUN echo "$USERNAME:x:$USER_UID:$USER_UID:$USERNAME User:/home/$USERNAME:/bin/sh" >> /etc/passwd && \
    echo "$USERNAME:x:$USER_UID:" >> /etc/group && \
    mkdir -p /home/$USERNAME && \
    chown -R $USER_UID:$USER_UID /home/$USERNAME
    
# User level
USER $USERNAME

# Jlink pre-build
ARG JAVA_MODULES="java.base,java.compiler,java.desktop,java.logging,java.management,java.naming,java.rmi,java.sql,java.transaction.xa,java.xml,jdk.crypto.ec,jdk.compiler,jdk.unsupported,java.security.jgss,java.security.sasl,java.net.http"
RUN bash -c "jlink \
    --add-modules "$JAVA_MODULES" \
    --compress=zip-2 \
    --no-header-files \
    --no-man-pages \
    --output /home/$USERNAME/jre"
