Description: ALB routing for ebapi service running on Elastic Beanstalk

Parameters:
  TenantId:
    Type: String
    Default: c3

  EnvId:
    Type: String
    Default: project

  ServiceName:
    Type: String
    Default: ebapi

  ContainerPort:
    Type: Number
    Default: 80

  PathPatterns:
    Type: CommaDelimitedList
    Default: /ebapi,/ebapi/*

  HealthCheckPath:
    Type: String
    Default: /ebapi/

  ListenerRulePriority:
    Type: Number
    Default: 11274

Resources:
  EbapiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: instance
      VpcId:
        Fn::ImportValue: !Sub '${TenantId}-VpcId'
      HealthCheckProtocol: HTTP
      HealthCheckPath: !Ref HealthCheckPath
      Matcher:
        HttpCode: '200-399'

  EbapiHttpsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub '${EnvId}-HttpsListenerArn'
      Priority: !Ref ListenerRulePriority
      Conditions:
        - Field: path-pattern
          Values: !Ref PathPatterns
      Actions:
        - Type: forward
          TargetGroupArn: !Ref EbapiTargetGroup

Outputs:
  EbapiTargetGroupArn:
    Description: ebapi target group arn
    Value: !Ref EbapiTargetGroup
    Export:
      Name: !Sub '${EnvId}-${ServiceName}TargetGroupArn'
