# export REPOSITORY_NAME=c3-api
# aws cloudformation deploy --stack-name ecr-$REPOSITORY_NAME --template-file cloudformation/ecr-private/template.cform.yaml --parameter-overrides RepositoryName=$REPOSITORY_NAME
# aws cloudformation delete-stack --stack-name ecr-$REPOSITORY_NAME
Description: ECR Repository

Parameters:
  RepositoryName:
    Type: String
    Description: Name of the ECR repository

  EmptyOnDelete:
    Type: String
    Default: "true"
    Description: Whether to empty the repository on stack deletion 
    AllowedValues:
      - "true"
      - "false"

  Mutability:
    Type: String
    Default: IMMUTABLE_WITH_EXCLUSION
    Description: Whether the repository is mutable 

Conditions:
  IsEmptyOnDelete: !Equals [!Ref EmptyOnDelete, "true"]

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      EmptyOnDelete: !If [IsEmptyOnDelete, true, false]
      ImageTagMutability: !Ref Mutability
      #TODO: EncryptionConfiguration
      ImageTagMutabilityExclusionFilters:
        - ImageTagMutabilityExclusionFilterType: "WILDCARD"
          ImageTagMutabilityExclusionFilterValue: "latest"
      Tags:
        - Key: Name
          Value: !Sub ${RepositoryName}-repository

Outputs:
  RepositoryArn:
    Description: ARN of the ECR repository
    Value: !GetAtt Repository.Arn
    Export:
      Name: !Sub "${RepositoryName}-RepositoryArn"

  LoginCommand:
    Description: Command to login to the ECR repository
    Value: !Sub "aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com"
    