ARG BASE_IMAGE="c3-ubi"
ARG UBI_VERSION="0.0"
ARG USER_NAME="code"

FROM ${BASE_IMAGE}:${UBI_VERSION}

ENV USER_NAME=${USER_NAME}

# Copy source code
WORKDIR "/home/${USER_NAME}/src"
COPY --chown=${USER_NAME} . .

 # Run build
RUN make
